### ISSUE TITLE
Popup window on problem in startlist

### ISSUE THREAD

**Issue by xkenia** [fvacek/quickbox#89] opened 2015-11-13 20:29 UTC
On error in start list, e.g. you put more runners in start list next to each other from same club, program should show popup window with this problem.

When someone do mistake (and you make some runner red) in startlist, popup window with this mistake.

This feature was raised on presentation in Sternberk.

**Comment by fvacek** [comment] 2015-11-14 20:37
I need more info, what does it mean "put more runners in start list next to each other"?

**Comment by xkenia** [comment] 2015-11-15 11:06
When someone do mistake (and you make some runner red( in startlist, popup window with this mistake.

**Comment by fvacek** [comment] 2015-11-22 21:32
I'd rather think about feature like 'fly-check' which can inspect start list for all (configurable) the known start lists bugs. In other words, report of all the reason for pop-up from this request.

**Comment by paukert** [comment] 2019-07-23 14:46
Duplicate of #262

**Closed** 2019-07-28 20:50 UTC
Labels: duplicate
