### ISSUE TITLE
Negative start time for runner

### ISSUE THREAD

**Issue by arnost00** [fvacek/quickbox#135] opened 2016-04-14 19:43 UTC
You cannot set negative start time (minus time) to racer. Sametimes you need to someone run earlier.

**Comment by fvacek** [comment] 2016-04-14 20:14
I'm not quite if it worth to do it. Negative numbers requires wider columns in reports etc.

**Comment by jmacura** [comment] 2016-04-16 20:04
I support such functionality. It is not common, but sometimes used and desired feature.
Q: Can be proposed start time suppressed by the use of "start" box? It would a sufficient workaround.

**Comment by fvacek** [comment] 2016-04-16 20:52
Do you mean, to use start station for negative starts?

**Comment by jmacura** [comment] 2016-04-16 21:02
exactly

**Comment by paukert** [comment] 2019-07-23 14:48
Duplicate of #241

**Closed** 2019-07-28 20:51 UTC
Labels: 5, duplicate, feature request
