### ISSUE TITLE
Single device for card reader is insufficient

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#31] opened 2015-05-16 23:00 UTC
Only one device can be selected for card reader plugin.

The device setting in separate dialog may be inconvenient.
Auto detection of read station would be nice

**Comment by fvacek** [comment] 2015-05-18 18:35
Do you suggest to support more card readers?

**Comment by Amaroun** [comment] 2015-05-18 19:10
Using several read si stations is quite common practice, so yes.

**Comment by fvacek** [comment] 2015-05-19 13:12
You can run as many quickevent instances as you want if you are using Postgres data storage. Isn't it an acceptable workaround?

**Comment by Amaroun** [comment] 2015-05-19 13:35
Don't think this is a great idea. If you have lets say two readout stations and three printers (again, used and seen this configuration many times) would be printers able to print just the right receipes?
And as "post row edits" icon is present on many forms, potential user errors based on beeing in one qb instance and have unposted edits in the other are likely.

**Comment by fvacek** [comment] 2015-05-20 08:36
I've designed QuickEvent to use arbitrary number of instances, each can read cards and print recipes. Recipe format shall be defined in event config, so right recipe will be always chosen.

If you are using client-server based architecture, you are always facing possible collision when editing same data. Good example is setting start time from more QE instances. Such a cases should be solved by table/row locking, transactions, dirty reading or something like that. Aggregating all the readers and printers to one instance doesn't do the thing.

**Comment by Amaroun** [comment] 2015-05-20 11:31
I understand peculiarities of client-server architectures, and I support and admire this approach.
What I'm less comfortable with is enforcing multiple instances of program for single user, as it brings confusion and advanced configuration to a simple use case.

**Comment by fvacek** [comment] 2015-05-20 11:40
As I've stated above: running more instance should be acceptable workaround for now. I'm focused on core functionality in this stage of project. So I'm not against the supporting of more station in feature but not now. What about changing this issue to feature request?

**Comment by paukert** [comment] 2019-07-23 14:35
Duplicate of #198

**Closed** 2019-07-28 20:48 UTC
Labels: 5, duplicate, feature request
