### ISSUE TITLE
No data manipulation in quickbox (linux)

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#22] opened 2015-05-05 15:03 UTC
Unable to store or import data from ORIS to file or posgre database.

After opening new file database log contains:

<INFO>[eventplugin.cpp] removing database: ""
<INFO>[eventplugin.cpp] Opening database file
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: cards Unable to execute statement SELECT cards.id AS cards__id, cards.siId AS cards__siId, runs.startTimeMs AS runs__startTimeMs, runs.timeMs AS runs__timeMs, runs.status AS runs__status, competitors.registration AS competitors__registration, classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM cards LEFT JOIN runs ON runs.id=cards.runId LEFT JOIN competitors ON competitors.id=runs.competitorId LEFT JOIN classes ON classes.id=competitors.classId WHERE (cards.stageId=0) ORDER BY cards.id DESC"
<WARN>[tablemodel.cpp] column "cards.id" not found in fields.
<WARN>[tablemodel.cpp] column "cards.siId" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "competitors.registration" not found in fields.
<WARN>[tablemodel.cpp] column "runs.startTimeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.timeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.status" not found in fields.
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: cards Unable to execute statement SELECT cards.id AS cards__id, cards.siId AS cards__siId, cards.printerConnectionId AS cards__printerConnectionId, runs.startTimeMs AS runs__startTimeMs, runs.timeMs AS runs__timeMs, runs.status AS runs__status, competitors.registration AS competitors__registration, classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM cards LEFT JOIN runs ON runs.id=cards.runId LEFT JOIN competitors ON competitors.id=runs.competitorId LEFT JOIN classes ON classes.id=competitors.classId WHERE (cards.stageId=0) ORDER BY cards.id DESC"
<WARN>[tablemodel.cpp] column "cards.id" not found in fields.
<WARN>[tablemodel.cpp] column "cards.siId" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "competitors.registration" not found in fields.
<WARN>[tablemodel.cpp] column "runs.startTimeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.timeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.status" not found in fields.
<WARN>[tablemodel.cpp] column "cards.printerConnectionId" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "classes"
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "classdefs"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: classes Unable to execute statement SELECT courses.name AS courses__name, courses.length AS courses__length, courses.climb AS courses__climb FROM classes LEFT JOIN classdefs ON classdefs.classId=classes.id AND (classdefs.stageId=0) LEFT JOIN courses ON courses.id=classdefs.courseId ORDER BY classes.name"
<WARN>[tablemodel.cpp] column "id" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.startTimeMin" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.startIntervalMin" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.vacantsBefore" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.vacantEvery" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.vacantsAfter" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.lastTimeMin" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.mapCount" not found in fields.
<WARN>[tablemodel.cpp] column "courses.name" not found in fields.
<WARN>[tablemodel.cpp] column "courses.length" not found in fields.
<WARN>[tablemodel.cpp] column "courses.climb" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "codes"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: coursecodes Unable to execute statement SELECT coursecodes.position AS coursecodes__position FROM coursecodes LEFT JOIN codes ON codes.id=coursecodes.codeId WHERE (coursecodes.courseId=0) ORDER BY coursecodes.position"
<WARN>[tablemodel.cpp] column "coursecodes.position" not found in fields.
<WARN>[tablemodel.cpp] column "codes.code" not found in fields.
<WARN>[tablemodel.cpp] column "codes.outOfOrder" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "competitors"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: competitors Unable to execute statement SELECT classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM competitors LEFT JOIN classes ON classes.id=competitors.classId ORDER BY competitors.id"
<WARN>[tablemodel.cpp] column "id" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "registration" not found in fields.
<WARN>[tablemodel.cpp] column "siId" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "runs"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: runs Unable to execute statement SELECT competitors.registration AS competitors__registration, competitors.siId AS competitors__siId, classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM runs LEFT JOIN competitors ON competitors.id=runs.competitorId LEFT JOIN classes ON classes.id=competitors.classId ORDER BY runs.id"
<WARN>[tablemodel.cpp] column "id" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitors.siId" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "registration" not found in fields.
<WARN>[tablemodel.cpp] column "runs.siId" not found in fields.
<WARN>[tablemodel.cpp] column "runs.startTimeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.timeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.status" not found in fields.
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: cards Unable to execute statement SELECT cards.id AS cards__id, cards.siId AS cards__siId, runs.startTimeMs AS runs__startTimeMs, runs.timeMs AS runs__timeMs, runs.status AS runs__status, competitors.registration AS competitors__registration, classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM cards LEFT JOIN runs ON runs.id=cards.runId LEFT JOIN competitors ON competitors.id=runs.competitorId LEFT JOIN classes ON classes.id=competitors.classId WHERE (cards.stageId=0) ORDER BY cards.id DESC"
<WARN>[tablemodel.cpp] column "cards.id" not found in fields.
<WARN>[tablemodel.cpp] column "cards.siId" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "competitors.registration" not found in fields.
<WARN>[tablemodel.cpp] column "runs.startTimeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.timeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.status" not found in fields.
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: cards Unable to execute statement SELECT cards.id AS cards__id, cards.siId AS cards__siId, cards.printerConnectionId AS cards__printerConnectionId, runs.startTimeMs AS runs__startTimeMs, runs.timeMs AS runs__timeMs, runs.status AS runs__status, competitors.registration AS competitors__registration, classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM cards LEFT JOIN runs ON runs.id=cards.runId LEFT JOIN competitors ON competitors.id=runs.competitorId LEFT JOIN classes ON classes.id=competitors.classId WHERE (cards.stageId=0) ORDER BY cards.id DESC"
<WARN>[tablemodel.cpp] column "cards.id" not found in fields.
<WARN>[tablemodel.cpp] column "cards.siId" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "competitors.registration" not found in fields.
<WARN>[tablemodel.cpp] column "runs.startTimeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.timeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.status" not found in fields.
<WARN>[tablemodel.cpp] column "cards.printerConnectionId" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "classes"
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "classdefs"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: classes Unable to execute statement SELECT courses.name AS courses__name, courses.length AS courses__length, courses.climb AS courses__climb FROM classes LEFT JOIN classdefs ON classdefs.classId=classes.id AND (classdefs.stageId=0) LEFT JOIN courses ON courses.id=classdefs.courseId ORDER BY classes.name"
<WARN>[tablemodel.cpp] column "id" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.startTimeMin" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.startIntervalMin" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.vacantsBefore" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.vacantEvery" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.vacantsAfter" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.lastTimeMin" not found in fields.
<WARN>[tablemodel.cpp] column "classdefs.mapCount" not found in fields.
<WARN>[tablemodel.cpp] column "courses.name" not found in fields.
<WARN>[tablemodel.cpp] column "courses.length" not found in fields.
<WARN>[tablemodel.cpp] column "courses.climb" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "codes"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: coursecodes Unable to execute statement SELECT coursecodes.position AS coursecodes__position FROM coursecodes LEFT JOIN codes ON codes.id=coursecodes.codeId WHERE (coursecodes.courseId=0) ORDER BY coursecodes.position"
<WARN>[tablemodel.cpp] column "coursecodes.position" not found in fields.
<WARN>[tablemodel.cpp] column "codes.code" not found in fields.
<WARN>[tablemodel.cpp] column "codes.outOfOrder" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "competitors"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: competitors Unable to execute statement SELECT classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM competitors LEFT JOIN classes ON classes.id=competitors.classId ORDER BY competitors.id"
<WARN>[tablemodel.cpp] column "id" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "registration" not found in fields.
<WARN>[tablemodel.cpp] column "siId" not found in fields.
<WARN>[querybuilder.cpp] Cannot retrieve fields for table: "runs"
<ERR>[sqltablemodel.cpp] "SQL Error: no such table: runs Unable to execute statement SELECT competitors.registration AS competitors__registration, competitors.siId AS competitors__siId, classes.name AS classes__name, COALESCE(lastName, '') || ' ' || COALESCE(firstName, '') AS competitorName FROM runs LEFT JOIN competitors ON competitors.id=runs.competitorId LEFT JOIN classes ON classes.id=competitors.classId ORDER BY runs.id"
<WARN>[tablemodel.cpp] column "id" not found in fields.
<WARN>[tablemodel.cpp] column "classes.name" not found in fields.
<WARN>[tablemodel.cpp] column "competitors.siId" not found in fields.
<WARN>[tablemodel.cpp] column "competitorName" not found in fields.
<WARN>[tablemodel.cpp] column "registration" not found in fields.
<WARN>[tablemodel.cpp] column "runs.siId" not found in fields.
<WARN>[tablemodel.cpp] column "runs.startTimeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.timeMs" not found in fields.
<WARN>[tablemodel.cpp] column "runs.status" not found in fields.

**Comment by fvacek** [comment] 2015-05-05 15:06
which event?

**Comment by Amaroun** [comment] 2015-05-05 17:21
tried on 2767 and 2959 events (DKP's Prague easter E3 and ZBM's middle regional championship)

**Comment by fvacek** [comment] 2015-05-06 14:13
duplicate of #23

**Closed by fvacek** 2015-05-06 14:13 UTC
